src/carbon_txt_validator/web/config/api.py, src/carbon_txt_validator/web/config/settings/base.py, src/carbon_txt_validator/web/middleware.py, tests/test_api_external.py
There is a bit of work needed to make endpoints agnostic about the trailing slash.
Fixes #8
=> Add trailing slashes for API endpoints

docs/conf.py, docs/deployment.md, pyproject.toml, src/carbon_txt_validator/web/config/settings/base.py, src/carbon_txt_validator/web/config/settings/development.py, src/carbon_txt_validator/web/middleware.py, tests/api_external.py, tests/test_api_external.py, uv.lock
This pull request includes several updates to the Carbon.txt Validator project, focusing on adding CORS support, updating version numbers, and refining the documentation and configuration files. The most important changes are summarized below:
* Added CORS support configuration in `docs/deployment.md` to allow requests from specific local origins and provide an option to accept requests from all origins.
* Updated `pyproject.toml` to include `django-cors-headers` as a dependency.
* Enabled CORS middleware in `src/carbon_txt_validator/web/config/settings/base.py`.
* Configured CORS settings in `src/carbon_txt_validator/web/config/settings/development.py` for development purposes.
* Updated the project version from `0.0.2` to `0.0.3` in `pyproject.toml`.
* Modified `docs/conf.py` to …
=> Add cors support and tidy up optional slash middleware

README.md, justfile, pyproject.toml, src/carbon_txt/cli.py, src/carbon_txt/exceptions.py, src/carbon_txt/web/config/settings/base.py, src/carbon_txt/web/config/settings/development.py, src/carbon_txt/web/config/settings/production.py, uv.lock
This pull request includes several updates to the `carbon-txt` project, focusing on improving the command line tool's functionality, enhancing error handling, and updating project settings. The most important changes include adding a new exception for insecure keys, updating the command line tool usage instructions, and modifying the `serve` command to support custom Django settings.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L45-R57): Updated instructions for running the command line tool with `uv run carbon-txt` and added examples for validating files and running a server.
* [`src/carbon_txt/cli.py`](diffhunk://#diff-a6ba177b10e6c53969a525a3552a70ac7f0b2b0d03a736e7fa7e76fbd3eaddbaR142-R165): Added handling for `InsecureKeyException` …
=> Ca gracefully fail server

.github/workflows/ci.yml, .gitignore, docs/installation.md, justfile, pyproject.toml, pytest.ini, uv.lock
This pull request includes significant updates to the documentation and build automation for the carbon-txt validator project. The most important changes involve the addition of detailed installation instructions, enhancements to the `justfile` for task automation, and updates to the project's dependencies.
* [`docs/installation.md`](diffhunk://#diff-8b042e3f94ca5c59a7cd990b950aec0073ea84fe811e7b22be51158d7b180d56L3-R69): Added comprehensive installation instructions for using `uv` and `just`, including commands for setting up the environment and running tasks.
* [`justfile`](diffhunk://#diff-deb9bb56fb122db0b605aa5b63f95a4665c905b18dd670e1fa6c877576a94ff1R12-R29): Added new tasks for running the CLI, showing environment variables, and generating coverage reports during tests. Updated …
=> Ca add coverage

src/carbon_txt/cli.py, src/carbon_txt/web/api.py, tests/test_api_external.py, tests/test_cli.py
This pull request introduces new functionality to generate and retrieve a JSON Schema representation of a `carbon.txt` file, along with some related changes to the CLI and API. It also includes test updates to validate the new functionality and removes some unnecessary imports and debug statements.
* Added a new CLI command to generate a JSON Schema representation of a `carbon.txt` file (`src/carbon_txt/cli.py`).
* Added a new API endpoint to retrieve the JSON Schema representation of a `carbon.txt` file (`src/carbon_txt/web/api.py`).
* Imported `json` and initialized `err_console` for error handling in CLI (`src/carbon_txt/cli.py`). [[1]](diffhunk://#diff-a6ba177b10e6c53969a525a3552a70ac7f0b2b0d03a736e7fa7e76fbd3eaddbaR1-L4) [[2]](diffhunk://#diff-a6ba177b10e6c53969a525a3552a70ac7f0b2b0d0 …
=> Add support for  json schema in API and CLI

src/carbon_txt/finders.py, tests/test_finders.py
This pull request introduces a new feature to handle 'via' HTTP headers in the `FileFinder` class and updates the corresponding tests. The changes include adding a method to check for 'via' headers, modifying the URI resolution logic to use this method, and adding new test cases to verify the functionality.
* [`src/carbon_txt/finders.py`](diffhunk://#diff-b4b173d63a512a58ae26461037b3a9f992f923eb31834e9de9db407e098f4e74R94-R113): Added a new method `_check_for_via_delegation` to check for 'via' headers in the HTTP response and return the URL specified in the header if present.
* [`src/carbon_txt/finders.py`](diffhunk://#diff-b4b173d63a512a58ae26461037b3a9f992f923eb31834e9de9db407e098f4e74L103-R143): Updated the `resolve_uri` method to use `_check_for_via_delegation` for handling 'via' …
=> Add initial http via lookup support

src/carbon_txt/cli.py, src/carbon_txt/exceptions.py, src/carbon_txt/finders.py, src/carbon_txt/parsers_toml.py, tests/test_cli.py
This pull request includes several changes to improve error handling and logging in the `carbon_txt` CLI application. The most important changes involve replacing `sys.exit` calls with `typer.Exit` for better integration with Typer, enhancing exception handling, and adding new tests for missing files.
* Replaced `sys.exit` calls with `typer.Exit` in various functions for better integration with Typer. [[1]](diffhunk://#diff-a6ba177b10e6c53969a525a3552a70ac7f0b2b0d03a736e7fa7e76fbd3eaddbaL54-R54) [[2]](diffhunk://#diff-a6ba177b10e6c53969a525a3552a70ac7f0b2b0d03a736e7fa7e76fbd3eaddbaL65-R69) [[3]](diffhunk://#diff-a6ba177b10e6c53969a525a3552a70ac7f0b2b0d03a736e7fa7e76fbd3eaddbaR83-R119) [[4]](diffhunk://#diff-a6ba177b10e6c53969a525a3552a70ac7f0b2b0d03a736e7fa7e76fbd3eaddbaL122-R135) …
=> Introduce use of app-specific exceptions

.github/workflows/release.yml, CHANGELOG.md, docs/architecture.md, docs/contributing.md, docs/index.md, docs/usage.md, justfile, pyproject.toml, src/carbon_txt/cli.py, uv.lock
This pull request includes several changes to automate the release process, update the project version, and improve the command-line interface. The most important changes include adding a GitHub Action for automated publishing, updating the version in `pyproject.toml`, and enhancing the `serve` command to respect custom host and port values.
* Added a GitHub Action workflow for automated publishing of the Python package to PyPI upon tagging a release. This includes steps for setting up dependencies, checking version consistency, and publishing the package. (`.github/workflows/release.yml`)
* Updated the project version to `0.0.8rc1` in `pyproject.toml`. (`pyproject.toml`)
* Updated `CHANGELOG.md` to include changes for version `0.0.8`, such as switching to more detailed exceptions, adding …
=> Updated changelog add first pass at tag release workflow

src/carbon_txt/web/api.py, tests/api_external.py, tests/test_api_external.py
This pull request includes several significant changes to the `src/carbon_txt/web/api.py` and related test files to improve error handling, logging, and test coverage.
* [`src/carbon_txt/web/api.py`](diffhunk://#diff-a7d46725d3e2c1b29c33a4ec373597f2fa5ca5faf2ba88f30fb82d47d4b2acbcR8-R14): Added imports for `finders`, `exceptions`, and `logging`. Introduced a `file_finder` instance and a `logger` instance to handle file resolution and logging respectively. Updated the `validate_url` function to include comprehensive error handling using `try`/`except` blocks and logging for various exceptions. [[1]](diffhunk://#diff-a7d46725d3e2c1b29c33a4ec373597f2fa5ca5faf2ba88f30fb82d47d4b2acbcR8-R14) [[2]](diffhunk://#diff-a7d46725d3e2c1b29c33a4ec373597f2fa5ca5faf2ba88f30fb82d47d4b2acbcL90-R120)
* …
=> Fix api response for via lookup - resolves #30

src/carbon_txt/cli.py
This pull request includes changes to improve the handling of subprocesses in the `src/carbon_txt/cli.py` file. The most important changes include switching from `os.system` to `subprocess.run` for executing the Granian server command and adding the necessary import for the `subprocess` module.
Improvements to subprocess handling:
* [`src/carbon_txt/cli.py`](diffhunk://#diff-a6ba177b10e6c53969a525a3552a70ac7f0b2b0d03a736e7fa7e76fbd3eaddbaR4): Added the `subprocess` import to handle subprocess execution more securely and robustly.
* [`src/carbon_txt/cli.py`](diffhunk://#diff-a6ba177b10e6c53969a525a3552a70ac7f0b2b0d03a736e7fa7e76fbd3eaddbaL152-R166): Replaced the `os.system` call with `subprocess.run` for running the Granian server, allowing for better argument handling and improved …
=> Add access logging for the bundled granian server

src/carbon_txt/validators.py, tests/test_api_external.py, tests/test_cli.py, tests/test_plugins/process_document.py
This PR introduces tests to demonstrate our plugins working, both on the command line, and via the django setting environment variables (this is the mechanism used to propogate the command line flags to the django app, because we don't always run `django.setup()` for every CLI command, so can't rely on just having the plugin config stored in the django config file.
Auto generated summary below:
---
This pull request includes several changes to improve the handling and testing of plugins in the `carbon_txt` project. The most important changes include updating the document processing logic, adding new test fixtures and test cases, and implementing a sample plugin for demonstration purposes.
* [`src/carbon_txt/validators.py`](diffhunk://#diff-ee4638d5f5c485cd75d48d52d7f2d32e24512f6ee6d1455711 …
=> Add tests for activating plugins via command line flags and django settings

docs/plugin_hooks.md, docs/plugins.md, src/carbon_txt/plugins.py
This pull request includes documentation updates and a minor code refactor to support the new plugin system for the Carbon.txt validator, as part of the work on #41 
The most important changes include the addition of detailed instructions on how to implement plugins and the reorganization of imports in the `plugins.py` file.
Documentation updates:
* [`docs/plugin_hooks.md`](diffhunk://#diff-5720adcaee912022673c4c789f9b16396419ff12b60a9913fe34799fb9511501R1-R34): Added a new document describing the plugin hooks used by the Carbon.txt validator, including an example of the `process_document` hook.
* [`docs/plugins.md`](diffhunk://#diff-416ed26bd34c304ad067cce7817d8cd1eb513c3b096a3761217b2d0297c6ffb1R1-R108): Added a new document explaining how to extend the Carbon.txt validator with …
=> Add docs with example of using a one-off plugin

src/carbon_txt/process_document.py, src/carbon_txt/schemas.py, src/carbon_txt/validators.py, src/carbon_txt/web/config/settings/base.py, tests/conftest.py, tests/test_internal_plugins.py
This PR introduces the first CSRD plugin where we look for the data points in a sample report detailed in #44.
We now support a new environment variable that allow us to run the validator with a CSRD parsing plugin enabled, so having this in the environment variables allows us to activate the plugin, `carbon_txt.process_document` that contains the CSRD parsing document.
I haven't given the file a more descriptive name yet, as I'm not sure if we want to have a `greenweb` namespace in the project or not yet.
```
ACTIVE_CARBON_TXT_PLUGINS = ("carbon_txt.process_document",)
```
Note - unfortunately, the CSRD parser is very slow on the first parse, especially when we are looking for lots of data points. We'd likely want to cache these, as well as check with the Arelle mailing to see if there …
=> Add test for activated internal csrd plugin

src/carbon_txt/exceptions.py, src/carbon_txt/finders.py, src/carbon_txt/process_csrd_document.py, src/carbon_txt/processors.py, src/carbon_txt/validators.py, src/carbon_txt/web/api.py, tests/conftest.py, tests/test_api_external.py, tests/test_internal_plugins.py, tests/test_validators.py
The PR improves the handling of exceptions raised when parsing links documents in a carbon.txt file. It's intended to handle the case of parsing CSRD reports, but should also work for any plugin that raises the same `NoMatchingDatapointsError` exception when parsing a document, and passes them along in its output.
---
This pull request includes several changes aimed at improving error handling, logging, and plugin management within the `carbon_txt` module. The most significant changes involve the addition of new exception classes, enhancements to logging, and updates to the plugin system to ensure better test isolation and error reporting.
* Added `NoMatchingDatapointsError` and `NoLoadableCSRDFile` exception classes to `src/carbon_txt/exceptions.py` for more specific error reporting.
* …
=> Add safer raising of exceptions via the API

pyproject.toml, src/carbon_txt/cli.py, src/carbon_txt/finders.py, src/carbon_txt/parsers_toml.py, src/carbon_txt/process_csrd_document.py, src/carbon_txt/processors.py, src/carbon_txt/validators.py, src/carbon_txt/web/api.py, src/carbon_txt/web/config/settings/base.py, tests/conftest.py, tests/test_api_external.py, tests/test_internal_plugins.py, tests/test_plugins/process_document.py, tests/test_processor_csrd.py, uv.lock
This pull request includes several changes to the logging system across the codebase, transitioning from the standard `logging` library to `structlog`. Additionally, it introduces a new dependency and updates some exception handling.
* Replaced `logging` with `structlog` across multiple files, including `src/carbon_txt/cli.py`, `src/carbon_txt/finders.py`, `src/carbon_txt/parsers_toml.py`, `src/carbon_txt/process_csrd_document.py`, `src/carbon_txt/processors.py`, `src/carbon_txt/validators.py`, `src/carbon_txt/web/api.py`, and various test files. [[1]](diffhunk://#diff-a6ba177b10e6c53969a525a3552a70ac7f0b2b0d03a736e7fa7e76fbd3eaddbaL17-R18) [[2]](diffhunk://#diff-b4b173d63a512a58ae26461037b3a9f992f923eb31834e9de9db407e098f4e74L14-R17) …
=> Add structlog for more manageable logging

src/carbon_txt/web/config/settings/base.py, src/carbon_txt/web/config/settings/production.py, src/carbon_txt/web/config/settings/test.py, tests/test_plugins/process_document.py
This pull request includes several changes to the logging configuration across different environments and a minor change to a test plugin. The main goal is to improve logging consistency and make the logs more suitable for each environment.
* [`src/carbon_txt/web/config/settings/base.py`](diffhunk://#diff-ccf5495a22ae8d4d5794a784e145dcebd0b028815a5e8ac2fe80dac75af7412dL47-R69): Updated the default logger configuration to set the "root" logger and adjusted the log levels for various loggers.
* [`src/carbon_txt/web/config/settings/production.py`](diffhunk://#diff-507dc1e5325b04d2c850d1d5d4c7ba8901bea0bf4f428f64ad39878e13bb0203R8-R14): Switched the console handler to use a "key_value" formatter, which is better suited for production.
* …
=> Add new defaults for seeing logger output

src/carbon_txt/exceptions.py, src/carbon_txt/processors.py, tests/test_api_external.py
After a chat with Fershad, we decided to add nicer readable label for the datapoints as well in errors.
---
This pull request includes several changes to improve error handling and data processing in the `carbon_txt` module. The most important changes include updating exception handling to include more detailed information, enhancing data retrieval methods, and improving test coverage.
* [`src/carbon_txt/exceptions.py`](diffhunk://#diff-31fca68fd6e7efba810d6cf2f090d68ea68109f7a2f60bfb98de905ac3842be2L39-L54): Modified the `NoMatchingDatapointsError` class to include a new attribute `datapoint_readable_label` for better error context. Updated the `__init__` method and the `__dict__` method to handle this new attribute.
* [`src/carbon_txt/processors.py`](diffhunk://#diff-52d4333509fb9634b01e …
=> Make sure we have readable versions of exceptions in our API

src/carbon_txt/validators.py, tests/test_api_external.py
This pull request includes changes to the validation logic in `src/carbon_txt/validators.py` and adds a new test case in `tests/test_api_external.py`. The most important changes are:
Validation logic update:
* Removed an unnecessary assertion in the `validate_contents` method to streamline the validation process. (`src/carbon_txt/validators.py`)
Testing improvements:
* Added a new test case `test_hitting_validate_with_zero_plugins_set` to ensure that the API correctly handles scenarios where no plugins are set, returning an empty dictionary/object. (`tests/test_api_external.py`)
=> Ca issue 59 check empty dict for fish

docs/adrs/01_adding_plugins_with_pluggy.md, docs/extending_with_plugins.md, docs/plugins.md, src/carbon_txt/process_csrd_document.py, src/carbon_txt/schemas.py, src/carbon_txt/validators.py, tests/conftest.py, tests/fixtures/aremythirdpartiesgreen.com.carbon-txt.toml, tests/fixtures/carbon-txt-test.toml, tests/test_api_external.py, tests/test_parsers.py, tests/test_processor_csrd.py, tests/test_schemas.py
Closes #62 
---
This pull request includes several changes to update terminology and improve code consistency in the `carbon_txt` project. The main changes involve renaming certain terms and updating the corresponding code and documentation.
Terminology updates:
* [`docs/adrs/01_adding_plugins_with_pluggy.md`](diffhunk://#diff-daf3404006eba8e6351e79286c8d3f054430adcc3ab66dab2e5ee9d0e1d078bcL133-R133): Changed `document.doctype` to `document.doc_type`.
* [`docs/extending_with_plugins.md`](diffhunk://#diff-4ca6ceedb0aeecf9fd64bdf50b4f586a58a2ac2694bf7fe411a48a0989e2e5b7L102-R103): Updated `Credential` to `Disclosure` and `doctype` to `doc_type`.
* [`src/carbon_txt/schemas.py`](diffhunk://#diff-b1c1bcdab791fdd66e23a8b693ca43c73de6d260cd115b4be6d44811d5b1c711L6-R30): Renamed `Provider` to …
=> Update our naming inline for 0.2 of the carbon.txt spec

src/carbon_txt/cli.py, src/carbon_txt/log_config.py, src/carbon_txt/validators.py, src/carbon_txt/web/api.py, src/carbon_txt/web/config/settings/base.py
This PR revisits how we handle logging, so it's controlled from one file, and also documents the use of both
1. structlog in used in our first-party code, and the use of `structlog.get_logger()`
2. the use of garden-variety logging in dependencies, that use the `logging.getLogger()` approach to create a logger
---
This pull request includes several changes to the `src/carbon_txt` project, focusing on logging improvements, CLI enhancements, and code cleanup. The most important changes include the addition of a new logging configuration, updates to the CLI for better plugin management, and various code improvements for clarity and functionality.
* Added a comprehensive logging configuration in `src/carbon_txt/log_config.py` to standardize logging across the application. This includes …
=> Tidy up logging so it's in one file

src/carbon_txt/process_csrd_document.py, src/carbon_txt/processors.py, src/carbon_txt/web/config/settings/base.py, tests/test_processor_csrd.py
This PR is the result of me rethinking how we use the Arelle XBRL parsing library in the carbon.txt validator, with a view to making it much easier to build plugins that query other CSRD datapoints that might be of interest.
The big change is that rather than there being a a single CSRD processor which contains a bunch of hard coded datapoints (i.e. "our" datapoints for tracking green energy), we:
1. move much of logic of using an XBRL parsing library into the `ArelleProcessor` which is a simplified wrapper around the Arelle's Python API
2. create a new `GreenwebCSRDProcessor` class that makes much more explicit use of the methods offered by the  `ArelleProcessor` directly. We're only really querying for a few datapoints, so we don't really need / want full access to what Arelle offers …
=> Make our CSRD processing code easier to make plugins from

src/carbon_txt/schemas.py, tests/fixtures/regression.strings-or-lists.carbon.txt.toml, tests/test_validators.py
This PR is added to fix the issue raised last week here:
https://github.com/thegreenwebfoundation/carbon-txt-site/issues/8
(Note: the issue might have been moved to a different repo - I'll try to update the link if so)
----
This pull request includes several changes to improve the handling of service types and validate file outputs. The most important changes include updating the `service_type` field to support both strings and lists, adding a new test fixture to catch a specific bug, and introducing a new validation test.
Updates to `service_type` handling:
* [`src/carbon_txt/schemas.py`](diffhunk://#diff-b1c1bcdab791fdd66e23a8b693ca43c73de6d260cd115b4be6d44811d5b1c711L20-R20): Modified the `service_type` field in the `Service` class to accept both a list of strings and a single string. …
=> Allow our validator to accept strings and lists of strings when listing services

README.md, pyproject.toml, src/carbon_txt/finders.py, tests/conftest.py, tests/http_mocks.py, tests/test_api_external.py, tests/test_cli.py, tests/test_finders.py, uv.lock
The previous test setup relied upon a number of "known", real, servers having particular test carbon.txt configurations available publicly, which was kinda brittle - both when that configuration changes or the servers go down, but it also means we can't run the test suite while working offline, for instance.
This PR introduces a set of fixtures for various scenarios under test which provide a URL already set up with the correct mocked response, and updates the tests to use them. The fixtures are:
- `mocked_carbon_txt_domain`
- `mocked_carbon_txt_url`
- `mocked_dns_delegating_carbon_txt_url`
- `mocked_http_delegating_carbon_txt_url`
- `mocked_404_carbon_txt_url`
Simply use these fixtures in your tests to receive a test URL with the appropriate mocks already set up.
TODO: We still have two …
=> Use http and dns mocks in test suite

pyproject.toml, src/carbon_txt/validators.py, src/carbon_txt/web/api.py, src/carbon_txt/web/validation_logging/middleware.py, tests/http_mocks.py, tests/test_api_external.py, tests/test_validation_logging.py, uv.lock
This adds a new validataion endpoint: `/api/validate/domain`, which
takes a FQDN in the `domain` parameter of the request body and attempts
to find a carbon.txt file for that domain following the standard logic:
checking in the root and .well-known directory for a carbon.txt, and
also checking for delegation via a DNS TXT record and the HTTP Via
header.
We also extend the ValidationResults type to optionally include the url
of the found carbon txt, so that this may be returned to the client (and
logged in the validation log middleware, which is itself updated to log
the new endpoint correctly)
=> Add domain validation API endpoint

.readthedocs.yml
Read the docs, our free documentation building service updated their system to require slightly different syntax to build docs.
This PR introduces the required change, and removes the part of the line that I don't think we need.
=> Fix the read the docs build process

.readthedocs.yml
This adds the missing invocation of 
```
sphinx-build docs/ $READTHEDOCS_OUTPUT/html/
```
to actually y'know... build the docs.
=> Fix read the docs build

.readthedocs.yml
In order to run `sphinx-build`, we need to wrap it with `uv run`, because otherwise the python path isn't set and the build machine for the docs doesn't know where to find `sphinx-build` the binary we use to generate our project documentation.
=> Ca fix read the docs build 2

src/carbon_txt/finders.py, src/carbon_txt/web/validation_logging/migrations/0001_initial.py, src/carbon_txt/web/validation_logging/models.py, tests/http_mocks.py, tests/test_api_external.py, tests/test_finders.py, tests/test_validators.py
When a request for a specific, full carbon.txt file url is requested, we
should not folllow DNS and HTTP delegation logic, and always validate
the specific file requested.
This comes from a discussion with Chris earlier today, in the context of
problems experienced by go.eco (and others) in validating carbon.txt
files hosted behind cloudflare, which adds a Via header which _doesn't_
comform to the standard we expect, and therefore causes an error on
validation.
This causes problems, as their carbon.txt shows as invalid when it
actually is not, for non-obvious reasons which aren't easily addressed
by the user themselves. Instead, much better to show them that their
carbon.txt is in fact valid, while we go about fixing the root cause of
the problem themselves.
It also makes more sense now …
=>   Never follow redirection when validating a URL

CHANGELOG.md, pyproject.toml
Bit of a formality, but for visibility:
I have bumped the version to v0.0.14, and also backfilled the changelog (from commit history), which had nothing since v0.0.11.
=> Version bump to v0.0.14, Update of changelog since v0.0.11

CHANGELOG.md, docs/adrs/02_improvements_to_delegation_and_domain_validation.md, docs/contributing.md, docs/deployment.md, docs/using_plugins.md, src/carbon_txt/finders.py, src/carbon_txt/processors.py, src/carbon_txt/validators.py, src/carbon_txt/web/api.py, tests/http_mocks.py, tests/test_api_external.py, tests/test_finders.py, tests/test_validation_logging.py, uv.lock
This PR updates the delegation logic to follow the new mechanism
outlined in ADR02, as well as adding tests that carbon.txt locations are
checked in the correct order, and that recursive delegation works as
specified. We also refactor the finder to make the order of lookups more
explicit.
=> New delegation mechanism

ansible/inventories/prod.yml, ansible/playbooks/deploy.yml, ansible/playbooks/templates/carbon_txt_api_dotenv.sh.j2, ansible/playbooks/templates/carbon_txt_api_local_config.py.j2, ansible/playbooks/templates/run_carbon_txt_api.sh.j2, ansible/playbooks/templates/systemd.carbon_txt_api.service.j2, docs/runbook.md, justfile, pyproject.toml, uv.lock
This PR introduces a deploy script intended to be run as a github action, so we have zero touch way to deploy the latest version of our validator API.
This is intended to replace the similar script in our infra repo, and is intended to only run when we push to the 'prod' branch.
----
This pull request introduces a comprehensive deployment setup for the `carbon.txt` API using Ansible, including new playbooks, templates, and documentation updates. The key changes focus on automating the deployment process, configuring necessary environment variables, and setting up systemd for service management.
* Added a new Ansible playbook `deploy.yml` to automate the deployment of the `carbon.txt` API, including tasks for verifying environment variables, setting up directories, and configuring systemd …
=> Add github action for deploying the service

.github/workflows/run-deploy.yml
This pull request introduces a new GitHub Actions workflow to automate the deployment of the latest version of the API service to the production environment. The workflow is triggered on pushes to the `prod` branch and ensures serialized deployments using the `turnstyle` action.
* [`.github/workflows/run-deploy.yml`](diffhunk://#diff-caba8d11eda0db195244705306667f508e47a95c5b91730b2356e242758a4269R1-R43): Added a GitHub Actions workflow to deploy the API service to production. It includes steps for code checkout, serialized deployment using `turnstyle`, and running an Ansible playbook with required secrets and environment variables.
=> Add github action for automatic deploying when we push to `prod`

docs/adrs/03_change_of_lookup_priority_order.md, src/carbon_txt/finders.py, tests/http_mocks.py, tests/test_finders.py
We want the DNS lookup to always take priority over all other carbon.txt lookup methods, so that domain  owners always have an opportunity to override carbon.txts set downstream in other infrastructure. Described in more detail in ADR03.
=> Ensure DNS record delegation takes priority

CHANGELOG.md, pyproject.toml
Version bump! This is all old stuff that we never did a release for (as we mostly needed it in the live site rather than the library, until now. We should watch that in future and try and release more frequently!
cc @mrchrisadams for your information, but will merge and deploy directly as it's not really at all controversial.
=> version bump: v0.0.16

src/carbon_txt/finders.py, src/carbon_txt/validators.py, tests/test_finders.py, uv.lock
This allows a user configured timeout length for carbon.txt lookups, which will be important in the GWF greencheck servcice, as we routiney look up carbon.txts for domains which have none, and which takes 5s by default.
=> Add an optional http_timeout argument to the FileFinder class
